version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/logs:/app/logs
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
